/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\androiddev\documents\github\nimrod_testing\nimcache\case.o c:\users\androiddev\documents\github\nimrod_testing\nimcache\case.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, readline_10484)(FILE* f);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, parseutilsInit)(void);
N_NOINLINE(void, parseutilsDatInit)(void);
N_NOINLINE(void, strutilsInit)(void);
N_NOINLINE(void, strutilsDatInit)(void);
N_NOINLINE(void, caseInit)(void);
N_NOINLINE(void, caseDatInit)(void);
STRING_LITERAL(TMP129, "A number please: ", 17);
STRING_LITERAL(TMP137, "The number is in the set: {0, 1, 2, 4, 5, 6, 7}", 47);
STRING_LITERAL(TMP138, "The number is 3 or 8", 20);
NI n_93003;
extern TFrame* frameptr_13038;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	parseutilsDatInit();
	strutilsDatInit();
	caseDatInit();
	initStackBottom();
	parseutilsInit();
	strutilsInit();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	caseInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, caseInit)(void) {
	NimStringDesc* LOC1;
	nimfr("case", "case.nim")
	nimln(4, "case.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP129))->data);
	nimln(5, "case.nim");
	nimln(5, "case.nim");
	LOC1 = 0;
	LOC1 = readline_10484(stdin);
	n_93003 = nsuParseInt(LOC1);
	nimln(6, "case.nim");
	switch (n_93003) {
	case 0 ... 2:
	case 4 ... 7:
	{
		nimln(7, "case.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP137))->data);
	}
	break;
	case 3:
	case 8:
	{
		nimln(8, "case.nim");
		printf("%s\015\012", (((NimStringDesc*) &TMP138))->data);
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
}

N_NOINLINE(void, caseDatInit)(void) {
}

