/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\androiddev\documents\github\nimrod_testing\nimcache\continue.o c:\users\androiddev\documents\github\nimrod_testing\nimcache\continue.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, readline_10484)(FILE* f);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, continueInit)(void);
N_NOINLINE(void, continueDatInit)(void);
extern TFrame* frameptr_13038;

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	continueDatInit();
	initStackBottom();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	continueInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, continueInit)(void) {
	nimfr("continue", "continue.nim")
	nimln(1, "continue.nim");
	while (1) {
		{
			NimStringDesc* x;
			nimln(2, "continue.nim");
			x = readline_10484(stdin);
			nimln(3, "continue.nim");
			{
				nimln(3, "continue.nim");
				if (!((x) && (x)->Sup.len == 0)) goto LA5;
				nimln(3, "continue.nim");
				goto LA2;
			}
			LA5: ;
			nimln(4, "continue.nim");
			printf("%s\015\012", (x)->data);
		} LA2: ;
	}
	popFrame();
}

N_NOINLINE(void, continueDatInit)(void) {
}

