/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\androiddev\documents\github\nimrod_testing\nimcache\for.o c:\users\androiddev\documents\github\nimrod_testing\nimcache\for.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, forInit)(void);
N_NOINLINE(void, forDatInit)(void);
STRING_LITERAL(TMP125, "Counting to ten: ", 17);
NI i_84016;
extern TFrame* frameptr_13038;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	forDatInit();
	initStackBottom();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	forInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}
N_NOINLINE(void, forInit)(void) {
	NI res_84018;
	nimfr("for", "for.nim")
	nimln(1, "for.nim");
	printf("%s\015\012", (((NimStringDesc*) &TMP125))->data);
	nimln(1450, "system.nim");
	res_84018 = 1;
	nimln(1451, "system.nim");
	while (1) {
		NimStringDesc* LOC2;
		nimln(1451, "system.nim");
		if (!(res_84018 <= 10)) goto LA1;
		nimln(1450, "system.nim");
		i_84016 = res_84018;
		nimln(3, "for.nim");
		nimln(3, "for.nim");
		LOC2 = 0;
		LOC2 = nimIntToStr(i_84016);
		printf("%s\015\012", (LOC2)->data);
		nimln(1453, "system.nim");
		res_84018 = addInt(res_84018, 1);
	} LA1: ;
	popFrame();
}

N_NOINLINE(void, forDatInit)(void) {
}

