/* Generated by Nimrod Compiler v0.9.4 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   "C:\Program Files (x86)\Nimrod\dist\mingw\bin\gcc.exe" -c  -w  -I"C:\Program Files (x86)\Nimrod\lib" -o c:\users\androiddev\documents\github\nimrod_testing\nimcache\resultvar.o c:\users\androiddev\documents\github\nimrod_testing\nimcache\resultvar.c */
#define NIM_INTBITS 64
#include "nimbase.h"

#include <stdio.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef NI TY84059[1];
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI TY84063[3];
typedef NI TY84068[4];
N_NIMCALL(NI, sumtillnegative_84003)(NI* x, NI xLen0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, initStackBottom)(void);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
N_NOINLINE(void, systemInit)(void);
N_NOINLINE(void, systemDatInit)(void);
N_NOINLINE(void, resultvarInit)(void);
N_NOINLINE(void, resultvarDatInit)(void);
NIM_CONST TY84063 TMP126 = {3,
4,
5}
;
NIM_CONST TY84068 TMP127 = {3,
4,
-1,
6}
;
extern TFrame* frameptr_13038;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (0 <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (0 <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	BeforeRet: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	(*s).prev = frameptr_13038;
	frameptr_13038 = s;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_13038 = (*frameptr_13038).prev;
}

N_NIMCALL(NI, sumtillnegative_84003)(NI* x, NI xLen0) {
	NI result;
	NI i_84046;
	NI i_84049;
	nimfr("sumTillNegative", "resultvar.nim")
	result = 0;
	i_84046 = 0;
	nimln(1530, "system.nim");
	i_84049 = 0;
	nimln(1531, "system.nim");
	while (1) {
		NI TMP125;
		nimln(1531, "system.nim");
		nimln(1531, "system.nim");
		if (!(i_84049 < xLen0)) goto LA1;
		nimln(1532, "system.nim");
		if ((NU)(i_84049) >= (NU)(xLen0)) raiseIndexError();
		i_84046 = x[i_84049];
		nimln(3, "resultvar.nim");
		{
			nimln(3, "resultvar.nim");
			if (!(i_84046 < 0)) goto LA4;
			nimln(4, "resultvar.nim");
			goto BeforeRet;
		}
		LA4: ;
		nimln(5, "resultvar.nim");
		nimln(5, "resultvar.nim");
		TMP125 = addInt(result, i_84046);
		result = (NI64)(TMP125);
		nimln(1533, "system.nim");
		i_84049 = addInt(i_84049, 1);
	} LA1: ;
	BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottom)(void) {
	void* volatile locals;
	locals = 0;
	locals = ((void*) (&locals));
	setStackBottom(locals);
}
void PreMain() {
	systemDatInit();
	systemInit();
	resultvarDatInit();
	initStackBottom();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMain)(void) {
	PreMain();
	resultvarInit();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_NOINLINE(void, resultvarInit)(void) {
	TY84059 LOC1;
	NI LOC2;
	NimStringDesc* LOC3;
	NI LOC4;
	NimStringDesc* LOC5;
	NI LOC6;
	NimStringDesc* LOC7;
	nimfr("resultvar", "resultvar.nim")
	nimln(7, "resultvar.nim");
	nimln(7, "resultvar.nim");
	nimln(7, "resultvar.nim");
	LOC2 = 0;
	LOC2 = sumtillnegative_84003(LOC1, 0);
	LOC3 = 0;
	LOC3 = nimIntToStr(LOC2);
	printf("%s\015\012", (LOC3)->data);
	nimln(8, "resultvar.nim");
	nimln(8, "resultvar.nim");
	nimln(8, "resultvar.nim");
	LOC4 = 0;
	LOC4 = sumtillnegative_84003(TMP126, 3);
	LOC5 = 0;
	LOC5 = nimIntToStr(LOC4);
	printf("%s\015\012", (LOC5)->data);
	nimln(9, "resultvar.nim");
	nimln(9, "resultvar.nim");
	nimln(9, "resultvar.nim");
	LOC6 = 0;
	LOC6 = sumtillnegative_84003(TMP127, 4);
	LOC7 = 0;
	LOC7 = nimIntToStr(LOC6);
	printf("%s\015\012", (LOC7)->data);
	popFrame();
}

N_NOINLINE(void, resultvarDatInit)(void) {
}

